### ISSUE TITLE
Error: Digest method not supported

### ISSUE THREAD

**Issue by maxiwer** [khaledosman/angular-realworld-example-app#3]
This error message appears after `npm start` command.
App version's that I'm using:
- node -> v16.12.0
- npm -> 8.1.0
- ng cli -> 13.0.1
```
⠦ Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (D:\MyProjects\angular-realworld-example-app\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (D:\MyProjects\angular-realworld-example-app\node_modules\webpack\lib\util\createHash.js:46:50)      
    at RawSource.updateHash (D:\MyProjects\angular-realworld-example-app\node_modules\webpack-sources\lib\RawSource.js:64:8)
    at NormalModule._initBuildHash (D:\MyProjects\angular-realworld-example-app\node_modules\webpack\lib\NormalModule.js:868:17)
    at handleParseResult (D:\MyProjects\angular-realworld-example-app\node_modules\webpack\lib\NormalModule.js:934:10)
    at D:\MyProjects\angular-realworld-example-app\node_modules\webpack\lib\NormalModule.js:1026:4
    at processResult (D:\MyProjects\angular-realworld-example-app\node_modules\webpack\lib\NormalModule.js:743:11)
    at D:\MyProjects\angular-realworld-example-app\node_modules\webpack\lib\NormalModule.js:807:5
    ```

**Comment by khaledosman** [comment]
yea I saw this error aswell after upgrading to angular v13, sounds like it has to do with webpack hash generation, ill revert the upgrade commit for now, but feel free to look into it and open a PR if you're interested
